---
name: CI
on: [push,pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.14.4'
    - run: go version
    - run: go mod download

    - name: golangci-lint
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.28.3
        golangci-lint run
    - name: test
      run: |
        bash scripts/codecov_test.sh
        curl -s https://codecov.io/bash > /tmp/codecov.sh
        bash /tmp/codecov.sh
